services:
  - type: web
    name: tts-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 11:app
    envVars:
      - key: SECRET_KEY
        value: 17f1af3d3e65cc76ea3894bc844a713d185f19f6e55b50f49cf3ebc4e9c466d8
      - key: DATABASE_URI
        value: postgresql://dangme_tts_user:lXw3MXTb9rDNpH5twofWWevQnVFOU47d@dpg-cvcom3rtq21c73a1po10-a/dangme_tts
      - key: AUDIO_DIR
        value: ./audio_files