services:
  - type: web
    name: tts-app
    runtime: docker
    port: 10000
    env: docker
    plan: free
    buildCommand: "docker build -t tts-app ."  # Build the Docker image
    startCommand: "gunicorn --bind 0.0.0.0:10000 main:app"  # Start the app
    envVars:
      - key: AUDIO_DIR
        value: /usr/src/app/audio_files
    healthCheckPath: /  # Optional: Health check endpoint
    autoDeploy: true  # Optional: Automatically deploy on Git push