services:
  - type: web
    name: tts-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: AUDIO_DIR
        value: ./audio_files
      - key: SECRET_KEY
        value:   # Replace with a secure key