services:
  - type: web
    name: tts-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: AUDIO_DIR
        value: ./audio_files
      - key: SECRET_KEY
        value: your-secret-key-here  # Replace with a secure key